# Generated by Django 3.0.5 on 2020-05-30 20:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), null=True, size=None),
        ),
        migrations.AddField(
            model_name='car',
            name='header_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='car',
            name='invoices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), null=True, size=None),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
