# Generated by Django 3.0.5 on 2020-05-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200530_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_layout',
            field=models.CharField(blank=True, choices=[('Inline 4', 'Inline 4'), ('Inline 5', 'Inline 5'), ('Inline 6', 'Inline 6'), ('Flat 4', 'Flat 4'), ('Flat 6', 'Flat 6'), ('V6', 'V6'), ('V8', 'V8')], max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(blank=True, choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Flex-Fuel', 'Flex-Fuel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='portrait',
            field=models.ImageField(default='user_silhouette.png', null=True, upload_to=''),
        ),
    ]
