# Generated by Django 3.0.5 on 2020-05-31 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200530_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='files',
        ),
        migrations.RemoveField(
            model_name='car',
            name='invoices',
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='portrait',
            field=models.ImageField(default='user_silhouette.png', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='CarFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('type', models.CharField(max_length=15)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.Car')),
            ],
        ),
    ]
