# Generated by Django 3.0.5 on 2020-05-31 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200530_2322'),
        ('api', '0004_auto_20200531_0139'),
    ]

    operations = [
    ]
